language: python

env:
  - 'UBUNTU_RELEASE=trusty'

python:
  - 2.7

install:
  - sudo pip install cffi six
  - wget http://launchpadlibrarian.net/173007451/python-ceilometer_2014.1-0ubuntu1_all.deb
  - sudo dpkg -i python-ceilometer_2014*.deb
  - git clone https://github.com/anchor/libmarquise.git ../libmarquise/
  - cd ../libmarquise/
  - autoreconf -i
  - ./configure
  - make
  - sudo make install
  - sudo su -c "echo '/usr/local/lib' > /etc/ld.so.conf.d/local.conf"
  - sudo ldconfig
  - cd -

script:
  - sudo python setup.py install
