language: python

python:
  - 3.4
  - 3.3
  - 3.2
  - 2.7
  - 2.6

before_install:
  - git clone https://github.com/anchor/libmarquise.git ../libmarquise/
  - cd ../libmarquise/
  - autoreconf -i
  - ./configure
  - make
  - sudo make install
  - sudo su -c "echo '/usr/local/lib' > /etc/ld.so.conf.d/local.conf"
  - sudo ldconfig
  - cd -
  - sudo pip install cffi

script:
  - sudo python setup.py install
