#!/bin/bash
set -eux

export LANG=en_US.UTF-8

MAJOR=$1
MINOR=$2
PATCH=$3
BUILDNO=$4
VERSION="${MAJOR}.${MINOR}.${PATCH}"
ROOT=$(realpath $(pwd))

echo
echo "BUILDING VERSION ${VERSION} - ${BUILDNO}"
echo

# Pre

if [ ! -d /etc/yum.repos.d ]; then
    sudo mkdir /etc/yum.repos.d
fi

sudo cp Vaultaire.repo /etc/yum.repos.d/
sudo yum update -y
sudo yum install -y zeromq-devel
sudo yum install -y zlib-devel

cd ..

git clone https://github.com/anchor/vaultaire-collector-common.git vaultaire-collector-common/
git clone https://github.com/anchor/vaultaire-common.git vaultaire-common/
git clone https://github.com/anchor/marquise.git marquise/

cd ceilometer-publisher-vaultaire

export LC_ALL=en_US.UTF-8
cabal list > /dev/null
sed -r -i "s,^(remote-repo: hackage.haskell.org.*)$,\1\nremote-repo: hackage.syd1.anchor.net.au:http://hackage.syd1.anchor.net.au/packages/archive," /home/jenkins/.cabal/config
cabal update
cabal sandbox init
cabal sandbox add-source ../vaultaire-common
cabal sandbox add-source ../marquise
cabal sandbox add-source ../vaultaire-collector-common
cabal install --only-dependencies
cabal build

mkdir packages

cp dist/build/ceilometer-publisher-vaultaire/ceilometer-publisher-vaultaire packages/ceilometer-publisher-vaultaire-${VERSION}-$BUILDNO
