#!/bin/bash
set -eux

export LANG=en_US.UTF-8

MAJOR=$1
MINOR=$2
PATCH=$3
VERSION="${MAJOR}.${MINOR}.${PATCH}"
ROOT=$(realpath $(pwd))

echo
echo "BUILDING VERSION ${VERSION} - ${PATCH}"
echo

# Install deps

if [ ! -d /etc/yum.repos.d ]; then
    sudo mkdir /etc/yum.repos.d
fi

sudo cp Vaultaire.repo /etc/yum.repos.d/

sudo yum update -y
sudo yum install -y zeromq-devel
sudo yum install -y zlib-devel

# Force creation of $HOME/.cabal/config
cabal list > /dev/null
sed -r -i "s,^(remote-repo: hackage.haskell.org.*)$,\1\nremote-repo: hackage.syd1.anchor.net.au:http://hackage.syd1.anchor.net.au/packages/archive," /home/jenkins/.cabal/config

mkdir artefacts

cabal update
cabal sandbox init
git clone https://github.com/anchor/vaultaire-collector-common.git ../vaultaire-collector-common/
git clone https://github.com/anchor/vaultaire-common.git ../vaultaire-common/
git clone https://github.com/anchor/marquise.git ../marquise/
cabal sandbox add-source ../vaultaire-collector-common/
cabal sandbox add-source ../vaultaire-common/
cabal sandbox add-source ../marquise/

cabal install

cp .cabal-sandbox/bin/* artefacts/

rm -rf "ceilometer-publisher-vaultaire-${VERSION}"
mv artefacts "ceilometer-publisher-vaultaire-${VERSION}"
mkdir -p packages

##
## Build an RPM package.
##

rpmdev-setuptree

# Make rpmbuild stop with the debuginfo packages.
echo '%debug_package %{nil}' > $HOME/.rpmmacros

tar czvf "$HOME/rpmbuild/SOURCES/ceilometer-publisher-vaultaire-${VERSION}.tar.gz" \
        "ceilometer-publisher-vaultaire-${VERSION}"
rpmbuild -bb --define "build_number $PATCH" --define "dist .el7" \
        $ROOT/pkg/centos/ceilometer-publisher-vaultaire.spec
find $HOME/rpmbuild/RPMS/ -type f | xargs -n 1 -I % cp % packages/

##
## Build a DEB package.
##

echo TODO
